########################################################
#          Environment for  Prepare Production 预线上环境配置   V4
########################################################
server:
  port: 8080
spring:
  profiles: v4
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.30.0.6:3306/hla?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false
    username: hla
    password: 060)fs4gvx3^pyr^
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 50000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  redis:
    host: 172.18.207.122
    port: 6379
    password: EwnDuUglmTunX24l
    database: 15

#配置参数For互道链接
hla:
  ops:
    mallId: 5b83bea8130b38000b394c79
    channel: hailan
    #注意host不要/结尾，后面拼接的url需要/打头！！！
    url:
      host: http://manage.preview.rongyi.com/ops/
      pathForTerminalList: /custom/getTerminalList
      pathForTerminalScreenShot: /custom/terminalScreenShot
      pathForQueryScreenResult: /custom/queryScreenResult
      pathForTerminalReboot: /custom/terminalReboot
      pathForTerminalTimeSet: /custom/terminalTimeSet
      pathForTerminalTimeInfo: /custom/terminalTimeInfo


  #云服务器上的空间名
  #【bucket的名称】.b0.upaiyun.com+/+【图片含后缀的名称】
  #例如：
  #你的bucketm名称：
  upyun:
    bucketName: rongyi
    username: gongzhen
    password: rynw87^%43
    url:
      host: .b0.upaiyun.com/
  filePath: /usr/local/servers/hla/file/local/
  hudao:
    appId: ntdf3d4ee23dadf28e6aec6268a29a6c
    appSecret: 61ca53afa8bcd6698058515ede60d88e
    host: https://open.hlzj.com:4000
    skuUrl: /api/v6/shop/product/query/get
    spuUrl: /api/v6/shop/product/spu/query/get
    groupUrl: /api/v6/shop/product/group/query/get
    accessTokenUrl: /api/v6/data/auth_token/get
