server:
  port: 80


spring:
  application:
    name: async
  profiles:
    active: dev #这里指定激活那个配置的空间

#配置日志 这里日志用xml去配置
logback:
  dir: /log



########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  profiles: dev

########################################################
#          不同环境         Environment for      注意：数据配置在这里
########################################################
---
spring:
  profiles: test
########################################################
#          不同环境         Environment for      注意：数据配置在这里
########################################################
---
spring:
  profiles: prod
