server:
    port: 9090

logging:
    level:
        tk.mybatis: TRACE

druid:
    url: jdbc:mysql://47.90.59.220:3306/antsoft?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: H8WDB8s111_II4vDef_
    initial-size: 5
    min-idle: 1
    max-active: 100
    test-on-borrow: true

mybatis:
    type-aliases-package: com.antsoft.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.antsoft.database.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql