server:
  port: 8007
spring:
  profiles:
    #这里指定激活那个配置的空间
    active: local
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
  #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #https://blog.csdn.net/zoeou/article/details/78629032
swagger:
  enabled: true
  title: oms-API
  description: API文档
  base-package:  com.op.copyems.Controller
  base-path: /**
  exclude-path: /error
  version: @project.version@




#配置日志
#  这里日志用xml去配置



mybatis:
  #为实体对象所在的包，跟数据库表一一对应
  #  type-aliases-package: com.arc.model.common
  #mapper文件的位置
  mapper-locations: classpath:mapper/*.xml




########################################################
#          不同环境 Environment for Development
########################################################
---
spring:
  profiles: dev

########################################################
#          Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  profiles: local
  datasource:
    #爆红不要紧张，没有问题的只是编辑工具不能识别造成的，本身是正确的
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1


########################################################
#          Environment for Testing
########################################################
---
spring:
  profiles: test

########################################################
#          Environment for Production
########################################################
---
spring:
  profiles: prod
