server:
  port: 5555


spring:
  profiles:
    active: local
  application:
    name: ray-zuul

########################################################
#          Environment for Development
########################################################
---
spring: 
  profiles: dev
eureka: 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client: 
    registry-fetch-interval-seconds: 5
    service-url: 
      defaultZone: http://zhjt:zhjt@192.168.28.26:8761/eureka/
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

########################################################
#          Environment for Localhost
#          首先向eureka注册自己，5555，服务名为service-zuul；以/api-a/ 开头的请求都指向service-ribbon；
#           以/api-b/开头的请求都指向service-feign；
# 依次运行这五个工程;打开浏览器访问：http://localhost:8769/api-a/hi?name=forezp ;
#浏览器显示：       hi forezp,i am from port:55555
# 打开浏览器访问：http://localhost:8769/api-b/hi?name=forezp ;
#浏览器显示： hi forezp,i am from port:8762  这说明zuul起到了路由的作用；
########################################################
---
spring: 
  profiles: local
eureka: 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client: 
    registry-fetch-interval-seconds: 5
    service-url: 
      defaultZone: http://sdmin:admin@127.0.0.1:8761/eureka/
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

########################################################
#          Environment for Testing
########################################################
---
spring: 
  profiles: test
eureka: 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client: 
    registry-fetch-interval-seconds: 5
    service-url: 
      defaultZone: http://zhjt:zhjt@192.168.61.38:8761/eureka/
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

########################################################
#          Environment for Production
########################################################
---
spring: 
  profiles: prod
eureka: 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client: 
    service-url: 
      defaultZone: http://zhjt:zhjt@192.168.61.25:8761/eureka/,http://zhjt:zhjt@192.168.61.26:8761/eureka/
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
