server:
  port: 8008

spring:
  profiles:
    active: local
    #这里指定激活那个配置的空间
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/

#配置日志
# 本点项目的日志以xml方式去配置，即： logback-spring.xml

mybatis:
  #为实体对象所在的包，跟数据库表一一对应
  #  type-aliases-package: com.arc.model.common
  #mapper文件的位置
  mapper-locations: classpath:mapper/*.xml




########################################################
#          不同环境         Environment for Localhost  注意：数据配置在这里
########################################################
---
spring:
  profiles: local
  datasource:
    #爆红不要紧张，没有问题的只是编辑工具不能识别造成的，本身是正确的
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
