server:
    port: 9090

logging:
    level:
        tk.mybatis: TRACE

druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://192.168.249.128:3307/db-test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
    slave:
        url: jdbc:mysql://192.168.249.128:3317/db-test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
mybatis:
    type-aliases-package: com.antsoft.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.antsoft.database.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql