server:
  servlet:
    context-path: /hla
  tomcat:
    accesslog:
    buffered: true
    directory: /data/apps/hla-manage/
    enabled: true
    file-date-format: .yyyy-MM-dd
    pattern: common
    prefix: access_log
#    rename-on-rotate: false
#    request-attributes-enabled: false
    rotate: true
    suffix: .log
    uri-encoding: utf-8
spring:
  servlet:

    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  security:
    user:
      name: admin
      password: admin
  profiles:
    active: prod         #指定激活那一份配置 dev local test product
  application:
    name: app-hla-manage
  resources:
    add-mappings: false

  #模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    locale: zh_CN
    time-zone: GMT+8


app:
  swagger2:
    base-package: com.rongyi.hla.controller
    title: 海澜之家在线文档HLA
    description: 测试
    version: 1.0
    terms-of-service-url: http://www.rongyi.com/
    contact-name: 叶超
    contact-url: 
    contact-email: lamymay@outlook.com

#mybatis:
mybatis-plus:
#为实体对象所在的包，跟数据库表一一对应
#实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.rongyi.model,com.rongyi.dto
#mapper文件的位置
  mapper-locations: classpath:mapper/*/*.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true




