########################################################
#          Environment for Test 开发环境配置
########################################################
server:
  port: 8089
spring:
  profiles: test
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.205:3306/hla?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false
    username: rongyi
    password: rongyi123$qwer
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 50000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

    #redis:
    # host: 192.168.1.205
    # port: 6379
  #  password: 123456789
  #  database: 15

#配置参数For互道链接
hla:
  ops:
    mallId: 51f9d7f731d6559b7d000163
    channel: hailan
    #注意host不要/结尾，后面拼接的url需要/打头！！！
    url:
      host: http://192.168.1.196/ops
      pathForTerminalList: /custom/getTerminalList
      pathForTerminalScreenShot: /custom/terminalScreenShot
      pathForQueryScreenResult: /custom/queryScreenResult
      pathForTerminalReboot: /custom/terminalReboot
      pathForTerminalTimeSet: /custom/terminalTimeSet
      pathForTerminalTimeInfo: /custom/terminalTimeInfo

  #云服务器上的空间名
  upyun:
    bucketName: rongyi
    username: gongzhen
    password: rynw87^%43
    url:
      host: .b0.upaiyun.com/
  filePath: /usr/local/servers/hla/file/test/
  hudao:
    appId: ntdf3d4ee23dadf28e6aec6268a29a6c
    appSecret: 61ca53afa8bcd6698058515ede60d88e
    host: https://open.hlzj.com:4000
    skuUrl: /api/v6/shop/product/query/get
    spuUrl: /api/v6/shop/product/spu/query/get
    groupUrl: /api/v6/shop/product/group/query/get
    accessTokenUrl: /api/v6/data/auth_token/get